import Head from 'next/head';
import image from '@/public/svg/agriculture.svg';
import Landing from '@/components/Landing';
import Paragraph from '@/components/Paragraph';
import useGlobalContext from '@/hooks/useGlobalContext';

const Agriculture = () => {
  const { metaContent } = useGlobalContext();
  const landingContent =
    'A solar power system for agriculture use is a system that utilizes solar panels to convert sunlight into electricity, which is then used to power various farming operations. The system typically includes solar panels, a solar inverter, and a battery bank to store the electricity generated by the panels. The electricity can be used to power irrigation systems, lighting, temperature control systems, and other equipment used in agriculture.';

  const para = [
    'Solar panels are the main component of a solar power system. They are made up of photovoltaic cells that convert sunlight into electricity. The size and number of solar panels needed for a solar power system for agriculture use will depend on the amount of electricity required for the farming operations.',
    'A solar inverter is another important component of a solar power system. It converts the direct current (DC) electricity produced by the solar panels into alternating current (AC) electricity, which is the type of electricity used in most farming operations. ',
    'A battery bank is also an essential component of a solar power system for agriculture use. It stores the electricity generated by the solar panels for use when sunlight is not available, such as during night time or cloudy weather.',

    "The benefits of a solar power system for agriculture use are many. Firstly, it can help reduce the cost of energy for the farm and decrease the farm's dependence on fossil fuels. Secondly, it is a clean and renewable source of energy that does not produce harmful emissions or contribute to climate change. Thirdly, a solar power system can provide a reliable source of electricity, even in remote or off-grid locations. Additionally, it can also help to improve the efficiency of farming operations, by powering irrigation systems, lighting and other equipment.",

    'Another benefit of using solar power in agriculture is that it can be used to power equipment and systems that are used in greenhouses. This can be extremely beneficial for farmers as it can help to reduce the costs associated with heating and cooling the greenhouse.',

    'Solar power systems can also be used to power water pumps, which can be used to pump water to irrigation systems and for other purposes. This can be extremely beneficial for farmers as it can help to reduce the costs associated with pumping water from wells or other sources.',

    'Solar power systems can also be used to power lighting systems, which can be used to light up greenhouses, barns, and other areas. This can be extremely beneficial for farmers as it can help to reduce the costs associated with lighting.',

    'Solar power systems can also be used to power temperature control systems, which can be used to control the temperature in greenhouses and other areas. This can be extremely beneficial for farmers as it can help to reduce the costs associated with heating and cooling.',

    'Solar power systems can also be used to power monitoring systems, which can be used to monitor the temperature, humidity, and other environmental factors in greenhouses and other areas. This can be extremely beneficial for farmers as it can help to improve the efficiency of farming operations.',

    "Overall, a solar power system for agriculture use is a cost-effective, clean and renewable source of energy that can help to improve the efficiency of farming operations and reduce the cost of energy for the farm. It's become a popular choice for farmers worldwide, as it can be used in a wide range of applications, from irrigation and lighting to temperature control and monitoring systems.",
  ];
  return (
    <>
      <Head>
        <title>BEST SOLAR FOR AGRICULTURE</title>
        <meta name="description" content={metaContent} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fav.png" />
      </Head>
      <main>
        <Landing
          page={'Solar For Agriculure'}
          image={image}
          landingContent={landingContent}
        />
        <Paragraph para={para} />
      </main>
    </>
  );
};
export default Agriculture;
