import Head from 'next/head';
import image from '@/public/svg/company.svg';
import Landing from '@/components/Landing';
import useGlobalContext from '@/hooks/useGlobalContext';
import Paragraph from '@/components/Paragraph';
import Lists from '@/components/Lists';
import CardList from '@/components/CardList';

import costSaving from '@/public/svg/services/company/costSaving.svg';
import brand from '@/public/svg/services/company/brand.svg';
import energy from '@/public/svg/services/company/energy.svg';
import environment from '@/public/svg/services/company/environment.svg';
import government from '@/public/svg/services/company/government.svg';
import Scroll from '@/components/ScrollToTop';

const Company = () => {
  const { metaContent } = useGlobalContext();
  const landingContent =
    'In an IT industry, the use of computer equipment and other electronics can lead to a significant demand for electricity. By installing a solar power system, IT companies can reduce their dependence on traditional sources of energy, save money on electricity bills, and contribute to a cleaner and greener environment. The system can be designed to meet the specific energy needs of the industry, taking into account factors such as building size, energy usage patterns, and budget.';
  const para1 = [
    'Data center consume large amounts of energy and are crucial to the operation of many businesses. By adopting a solar power system, data centers can reduce their dependence on traditional sources of energy, save money on electricity bills, and contribute to a cleaner and greener environment. The system can be designed to meet the specific energy needs of the data center, taking into account factors such as building size, energy usage patterns, and budget.',
  ];

  const typesTitle =
    'There are two main types of solar power systems for the IT industry: grid-tied and off-grid.';
  const types = [
    {
      title: ' Grid-tied systems',
      info: 'This type of system is connected to the electricity grid and is designed to complement the energy generated by the grid. When the solar panels generate more electricity than is being used, the excess energy is fed back into the grid, earning credits that can be used when the building needs more energy than is being generated by the panels.',
    },
    {
      title: ' Off-grid systems',
      info: 'This type of system operates independently of the electricity grid and is designed to provide a building with all its energy needs. Off-grid systems typically include battery storage, allowing the IT industry to have a backup source of power in case of a power outage.',
    },
  ];

  const para2 = [
    'Both types of systems can be customized to meet the specific energy needs of the IT industry. Factors to consider when choosing a solar power system include the size of the building, energy usage patterns, and budget. With the advancement in technology, solar panels have become more efficient and cost-effective, making it possible for IT companies of all sizes to adopt sustainable energy practices.',
  ];

  const cardTitle = 'Why should IT industry go for solar power system';

  const cardContent = [
    {
      title: 'Cost savings',
      icon: costSaving,
      info: 'Solar power systems can significantly reduce electricity costs for IT companies.',
    },
    {
      title: 'Environmental benefits',
      icon: environment,

      info: "Adopting solar power can reduce a company's carbon footprint and contribute to a greener future.",
    },
    {
      title: 'Energy security',
      icon: energy,

      info: 'Solar power systems provide a reliable and sustainable source of energy, reducing dependence on traditional power grids.',
    },
    {
      title: 'Brand reputation',
      icon: brand,
      info: 'Companies that adopt sustainable energy practices can enhance their brand reputation and appeal to eco-conscious consumers.',
    },
    {
      title: 'Government incentives',
      icon: government,
      info: 'Many countries offer tax credits and other incentives for companies that adopt renewable energy technologies like solar power.',
    },
  ];

  const benefitTitle =
    'Data centers require a lot of electricity to run their servers and cooling systems, and this electricity is usually generated by burning fossil fuels, which contributes to climate change. Therefore, going for a solar power system can offer several benefits for data centers, including:';

  const benefits = [
    {
      title: ' Cost savings',
      info: 'Data centers typically consume a lot of electricity, and the cost of electricity can be a significant portion of their operating expenses. A solar power system can help data centers reduce their electricity bills and save money in the long run.',
    },
    {
      title: 'Sustainability',
      info: 'Solar power is a clean and renewable source of energy that does not produce harmful emissions. By using a solar power system, data centers can reduce their carbon footprint and contribute to a more sustainable future.',
    },
    {
      title: 'Reliability',
      info: 'Solar power systems can provide a reliable source of electricity for data centers. In case of power outages or other disruptions to the electrical grid, a solar power system can provide a backup source of electricity.',
    },
    {
      title: '  Brand image',
      info: 'Many consumers are becoming increasingly environmentally conscious and are looking for businesses that are committed to sustainability. By using a solar power system, data centers can improve their brand image and appeal to environmentally conscious consumers.',
    },
    {
      title: ' Government incentives',
      info: 'Many governments offer incentives for businesses that invest in renewable energy systems such as solar power systems. These incentives can include tax credits, grants, and other financial benefits.',
    },
  ];

  const lastPara = [
    'In summary, data centers should go for a solar power system to save on operating expenses, reduce their carbon footprint, provide a reliable source of electricity, improve their brand image, and take advantage of government incentives. By using solar power, data centers can contribute to a more sustainable future while also improving their bottom line.',
  ];

  return (
    <>
      <Head>
        <title>BEST SOLAR FOR COMPANY</title>
        <meta name="description" content={metaContent} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fav.png" />
      </Head>
      <main>
        <Landing
          page={'Solar For IT Industry'}
          image={image}
          landingContent={landingContent}
        />
        <Paragraph para={para1} />
        <Lists content={types} title={typesTitle} />
        <CardList content={cardContent} title={cardTitle} />
        <Lists content={benefits} title={benefitTitle} />
        <Paragraph para={lastPara} />
        <Scroll />
      </main>
    </>
  );
};
export default Company;
