import Head from 'next/head';
import image from '@/public/svg/industry.svg';
import Landing from '@/components/Landing';
import CardList from '@/components/CardList';
import Paragraph from '@/components/Paragraph';

import solarpanel from '@/public/svg/services/housing/solarpanel.svg';
import inverter from '@/public/svg/services/housing/inverter.svg';
import monitoring from '@/public/svg/services/housing/monitoring.svg';
import mounting from '@/public/svg/services/industry/mounting.svg';
import wiring from '@/public/svg/services/industry/wiring.svg';
import Scroll from '@/components/ScrollToTop';
import { useSelector } from 'react-redux';

const Industry = () => {
  const { metaContent } = useSelector((store) => store.post);

  const landingContent =
    'A solar power system for commercial and industrial (C&I) applications is a renewable energy system that uses solar panels to generate electricity for commercial and industrial buildings. The system works by capturing the energy from the sun through solar panels and converting it into usable electricity that can power commercial and industrial appliances, lighting, and other electrical devices.There are different types of solar power systems available for commercial and industrial applications, including rooftop systems, ground-mounted systems, and carport systems. Rooftop systems are mounted on the roof of a building, ground-mounted systems are installed on the ground near the building, and carport systems are installed in parking lots to provide shade for cars while generating electricity.';

  const listTitle =
    'The solar power system for commercial and industrial applications typically consists of the following components:';

  const lists = [
    {
      title: 'Solar Panels',
      icon: solarpanel,
      info: 'Solar panels are the most important component of a solar power system. They are made up of photovoltaic cells that convert sunlight into electricity. The number of solar panels required for a commercial or industrial installation depends on the size of the building and the energy requirements.',
    },
    {
      title: 'Inverter',
      icon: inverter,
      info: ' The inverter is a device that converts the direct current (DC) electricity generated by the solar panels into alternating current (AC) electricity that can be used to power commercial and industrial appliances and other devices.',
    },
    {
      title: 'Mounting System',
      icon: mounting,
      info: 'The mounting system is used to secure the solar panels to the roof or ground. It must be able to withstand wind, rain, and other environmental conditions.',
    },
    {
      title: 'Electrical Wiring and Switchgear',
      icon: wiring,
      info: "Electrical wiring and switchgear are used to connect the solar power system to the building's electrical system. This includes wiring for the inverter, solar panels, and battery (if applicable).",
    },
    {
      title: 'Monitoring System',
      icon: monitoring,
      info: 'A monitoring system allows business owners to track the performance of their solar power system. This includes information such as how much electricity is being generated, how much energy is being used, and how much is being fed back into the grid (if applicable).',
    },
  ];

  const para = [
    'The installation of a solar power system in a commercial or industrial building can offer several benefits. First, it can significantly reduce electricity bills by generating electricity from a renewable source. Second, it can help reduce the carbon footprint of the business by reducing reliance on fossil fuels. Third, it can provide a reliable source of electricity during power outages. Finally, it can increase the value of the property as solar power systems are becoming more and more popular among business owners.',

    "However, there are also some considerations to keep in mind when installing a solar power system in a commercial or industrial building. These include the initial cost of installation, which can be expensive, and the fact that the system's effectiveness is dependent on the amount of sunlight that the panels receive. Additionally, the installation of solar panels may require permits from the local government and compliance with regulations such as fire codes and building codes.",

    'In summary, a solar power system for commercial and industrial applications is a renewable energy system that uses solar panels to generate electricity for commercial and industrial buildings. It consists of solar panels, an inverter, a mounting system, electrical wiring and switchgear, and a monitoring system. The installation of a solar power system can offer several benefits, including reduced electricity bills, reduced carbon footprint, reliable electricity during power outages, and increased property value.',
  ];

  return (
    <>
      <Head>
        <title>BEST SOLAR FOR INDUSTRY</title>
        <meta name="description" content={metaContent} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fav.png" />
      </Head>
      <main>
        <Landing
          page={'Solar For Industry'}
          image={image}
          landingContent={landingContent}
        />
        <CardList content={lists} title={listTitle} />
        <Paragraph para={para} />
        <Scroll />
      </main>
    </>
  );
};
export default Industry;
