import Content from '@/components/Content/Content';
import Scroll from '@/components/ScrollToTop/ScrollToTop';
import SideBar from '@/components/sidebar/sidebar';
import services from '@/data/services';
import Head from 'next/head';
import { FaCheckCircle } from 'react-icons/fa';

const ResidentialSolar = () => {
  const keywords =
    'Solar power solution, Residential properties, Solar panels, Electricity generation, Inverter, Direct current (DC) electricity, Alternating current (AC) electricity, Excess electricity, Battery storage, Net metering, Cost savings, Energy independence, Environmental benefits, Low maintenance, Increased property value, Grid-Tied Solar Systems, Off-Grid Solar Systems.';

  const metaDescription =
    'Discover the benefits of residential solar power systems, from cost savings and energy independence to environmental benefits and increased property value. Understand the differences between grid-tied and off-grid systems and learn how solar panels, inverters, and net metering play a role in harnessing clean and renewable energy for residential properties.';
  const content = (
    <div>
      <p>
        A solar power solution for residential properties typically involves
        installing solar panels on the roof or property grounds. These panels
        convert energy from the sun into electricity that can be used to power a
        home. In addition to the panels, a solar power system for a home also
        includes an inverter, which converts the direct current (DC) electricity
        produced by the panels into alternating current (AC) electricity, which
        is the type of electricity used in most homes. Any excess electricity
        generated by the panels can be stored in batteries or sent back to the
        grid through a process called net metering. The cost of a solar power
        system can vary depending on the size of the system and location, but it
        can ultimately lead to significant savings on electricity bills over
        time.
      </p>
      <p className="margin">
        There are mainly two types of residential solar power systems:
      </p>
      <ul>
        <li className="margin">
          <strong> Grid-Tied Solar Systems: </strong> These are connected to the
          electrical grid and provide electricity to the home while also sending
          any excess power back to the grid. Advantages: No need for battery
          storage, grid acts as a backup, can reduce electricity bills, can earn
          credits for excess energy sent back to the grid. Disadvantages:
          Doesn't work during power outages, dependence on utility company for
          backup, can be affected by grid maintenance.
        </li>
        <li className="margin">
          <strong> Off-Grid Solar Systems:</strong> These are independent of the
          electrical grid and rely solely on battery storage for power.
          Advantages: Complete energy independence, no dependence on utility
          company, can work during power outages. Disadvantages: Need for
          expensive battery storage, requires regular maintenance, can be less
          efficient, less cost-effective than grid-tied systems.
        </li>
      </ul>
      <p>
        Both types of systems have their own advantages and disadvantages, and
        the choice between them depends on a homeowner's energy needs, budget,
        and location.
      </p>
      <p>Some of the benefit of solar power for residential:</p>
      <ul>
        <li className="margin">
          <FaCheckCircle />
          <strong> Cost savings:</strong> Solar power can significantly reduce
          or even eliminate electricity bills, as the power generated by the
          panels can be used to power a home.
        </li>
        <li className="margin">
          <FaCheckCircle />
          <strong> Energy independence:</strong> With a solar power system, a
          home can produce its own electricity, reducing dependence on
          traditional utility companies.
        </li>
        <li className="margin">
          <FaCheckCircle />
          <strong> Environmental benefits:</strong> Solar power is a clean,
          renewable energy source that does not produce any emissions or
          pollutants, making it an environmentally friendly option.
        </li>
        <li className="margin">
          <FaCheckCircle />
          <strong>Durability and low maintenance:</strong> Solar panels have no
          moving parts and require very little maintenance, making them a
          durable and reliable energy source.
        </li>
        <li className="margin">
          <FaCheckCircle />
          <strong> Increased property value:</strong> A solar power system can
          increase the value of a home, making it more attractive to potential
          buyers
        </li>
      </ul>
    </div>
  );
  return (
    <>
      <Head>
        <title>RESIDENTIAL SOLAR SYSTEM INSTALLATION</title>
        <meta name="description" content={metaDescription} />
        <meta name="keywords" content={keywords} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/fav.png" />
      </Head>
      <main>
        <Content title={'Residential Solar System'} description={content} />
        <SideBar items={services} name="Services" />

        <Scroll />
      </main>
    </>
  );
};
export default ResidentialSolar;
